version: '3.7'

services:
  postgres:
    image: postgres:14.2-alpine3.15
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_pv:/var/lib/postgresql/data
  api:
    depends_on:
      - postgres
    image: ghcr.io/drzin-dev/anodos:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: ${MODE:-development}
    ports:
      - 8000:80
    environment:
      PORT: 80
      MODE: production

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_SYNC: "true"
      POSTGRES_DROP: "false"
      POSTGRES_LOGGING: "false"
    volumes:
      - ./src:/usr/src/app/src

volumes:
  postgres_pv:
