version: '3.7'

services:
  postgres:
    image: postgres:14.2-alpine3.15
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_pv:/var/lib/postgresql/data

volumes:
  postgres_pv:
