name: Staging CD

on:
  push:
    branches: [main]

jobs:
  check-file-changed:
    runs-on: ubuntu-latest
    outputs:
      api_changed: ${{ steps.api-changed-files.outputs.any_changed }}
      todolist_changed: ${{ steps.todolist-changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: api-changed-files
        uses: tj-actions/changed-files@v14.1
        with:
          since_last_remote_commit: 'true'
          files: |
            api/
      - name: Get changed files
        id: todolist-changed-files
        uses: tj-actions/changed-files@v14.1
        with:
          since_last_remote_commit: 'true'
          files: |
            todolist/

  api-build:
    if: needs.check-file-changed.outputs.api_changed == 'true'
    needs:
      - check-file-changed
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "dockerize api"

  api-deploy:
    needs:
      - check-file-changed  
    runs-on: ubuntu-latest
    steps:
      - run: echo "dockerize api"

  todo-list-build:
    if: needs.check-file-changed.outputs.todolist_changed == 'true'
    needs:
      - check-file-changed
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./todolist
    steps:
      - uses: actions/checkout@v2