name: Staging CD

on:
  push:
    branches: [main]

jobs:
  check-file-changed:
    runs-on: ubuntu-latest
    outputs:
      api_changed: ${{ steps.api-changed-files.outputs.any_changed }}
      todo_list_changed: ${{ steps.todo-list-changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: api-changed-files
        uses: tj-actions/changed-files@v14.1
        with:
          since_last_remote_commit: 'true'
          files: |
            api/
      - name: Get changed files
        id: todo-list-changed-files
        uses: tj-actions/changed-files@v14.1
        with:
          since_last_remote_commit: 'true'
          files: |
            todolist/

  api-build-push:
    if: needs.check-file-changed.outputs.api_changed == 'true'
    needs:
      - check-file-changed
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: true
          push: true
          context: ./api
          file: ./api/Dockerfile
          target: production
          tags: |
            ghcr.io/drzin-dev/anodos:latest

  api-deploy:
    needs:
      - api-build-push
    runs-on: ubuntu-latest
    steps:
      - run: echo "dockerize api"
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Adding Known Hosts
        run: ssh-keyscan -H 206.189.38.174 >> ~/.ssh/known_hosts
      - name: Deploy Staging Server
        run: ssh root@206.189.38.174 'cd /root/deployment && make DEPLOY_ANODOS_STAGING'

  todo-list-build:
    if: needs.check-file-changed.outputs.todo_list_changed == 'true'
    needs:
      - check-file-changed
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./todolist
    steps:
      - uses: actions/checkout@v2

  todo-list-publish-test-flight:
    if: needs.check-file-changed.outputs.todo_list_changed == 'true'
    needs:
      - check-file-changed
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./todolist
    steps:
      - uses: actions/checkout@v2